channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - pip=23.3.1
  - python=3.11.6
  - pytorch=2.1.0
  - pytorch-cuda=12.1
  - torchaudio=2.1.0
  - torchvision=0.16.0
  - pip:
      - albumentations==1.4.3
      - black==23.9.1
      - isort==5.12.0
      - kaggle==1.5.16
      - lightning==2.2.0
      - matplotlib==3.8.1
      - mypy==1.7.1
      - numpy==1.26.2
      - opencv-python==4.8.1.78
      - pandas==2.1.1
      - pre-commit==3.6.0
      - pylint==3.0.0
      - seaborn==0.13.0
      - tensorboard==2.14.1
      - tensorflow==2.14.0
      - timm==0.9.7
      - torch-tb-profiler==0.4.3
      - torchmetrics==1.3.0
      - tqdm==4.66.1
