name: kaggle_classification
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - lightning=2.0.9
  - python=3.11.6
  - pytorch=2.1.0
  - pytorch-cuda=12.1
  - torchaudio=2.1.0
  - torchvision=0.16.0
  - pip:
      - albumentations==1.3.1
      - black==23.9.1
      - isort==5.12.0
      - matplotlib==3.8.1
      - mypy==1.5.1
      - numpy==1.26.2
      - opencv-python==4.8.1.78
      - pandas==2.1.1
      - pylint==3.0.0
      - tensorboard==2.14.1
      - tensorflow==2.14.0
      - timm==0.9.7
      - tqdm==4.66.1
