version: '3'

env:
  DEFAULT_ENVIRONMENT_NAME: kaggle_classification

includes:
  petals:
    taskfile: ./kaggle_classification/data/petals/Taskfile.yml
    dir: ./kaggle_classification/data/petals/

tasks:
  default:
    cmds:
      - task --list

  init:
    desc: Build environment & download all data
    cmds:
      - task: build
      - task: download

  build:
    desc: Build environment
    cmds:
      - |
        if mamba info --envs | grep -q $DEFAULT_ENVIRONMENT_NAME; then
          echo "$DEFAULT_ENVIRONMENT_NAME already exists";
        else
          conda install -y mamba; mamba env create -f environment.yml -n $DEFAULT_ENVIRONMENT_NAME;
        fi
  
  download:
    desc: Download all data
    cmds:
      - task: petals:download
  
  train:
    desc: Run classification training
    cmds:
      - mamba run --live-stream -n ${DEFAULT_ENVIRONMENT_NAME} python -m kaggle_classification.train {{.CLI_ARGS}};

  lint:
    desc: Run linting
    cmds:
      - mamba run --live-stream -n ${DEFAULT_ENVIRONMENT_NAME} pre-commit run --all-files;
