version: '3'

env:
  DEFAULT_ENVIRONMENT_NAME: kaggle_classification

includes:
  base:
    taskfile: ../Taskfile.yml
    dir: ../
    internal: true

tasks:
  build:
    desc: Setup environment
    cmds:
      - task: base:build
      - |
        if [[ -z "${CONDA_DEFAULT_ENV}" ]]; then
          mamba run --live-stream -n ${DEFAULT_ENVIRONMENT_NAME} kaggle competitions download -c tpu-getting-started;
          mamba run --live-stream -n ${DEFAULT_ENVIRONMENT_NAME} python convert.py;
        else
          mamba run --live-stream kaggle competitions download -c tpu-getting-started;
          mamba run --live-stream python convert.py;
        fi
