name: CI

on: [pull_request, push]

env:
  ENVIRONMENT_NAME: kaggle_classification

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: arduino/setup-task@v1
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: $ENVIRONMENT_NAME
        environment-file: environment.yml
        miniforge-variant: Mambaforge
        use-mamba: true
    - name: Run pre-commit
      shell: bash -l {0}
      run: task lint
